- alias: live
  config:
    configmap: controller-conf
    namespace: hasura
  data: null
  kubeContext: abandoned78
  name: abandoned78
- alias: hasura
  config:
    configmap: controller-conf
    namespace: hasura
  data: null
  kubeContext: caduceus20
  name: caduceus20
- alias: production
  config:
    configmap: controller-conf
    namespace: hasura
  data: null
  kubeContext: arranger10
  name: arranger10
